from gym.envs.RoboSkate.RoboSkateNumerical import RoboSkateNumerical
from gym.envs.RoboSkate.RoboSkateMultiInputPolicy import RoboSkateMultiInputPolicy
from gym.envs.RoboSkate.RoboSkateSegmentation import RoboSkateSegmentation
from gym.envs.RoboSkate.RoboSkateNumericalReduced import RoboSkateNumericalReduced
from gym.envs.RoboSkate.RoboSkateSegmentationReduced import RoboSkateSegmentationReduced
from gym.envs.RoboSkate.RoboSkateMultiInputPolicyReduced import RoboSkateMultiInputPolicyReduced








