from gym.envs.RoboSkate.RoboSkateNumerical import RoboSkateNumerical
from gym.envs.RoboSkate.RoboSkateMultiInputPolicy import RoboSkateMultiInputPolicy
from gym.envs.RoboSkate.RoboSkateSegmentation import RoboSkateSegmentation
from gym.envs.RoboSkate.RoboSkateNumericalReduced import RoboSkateNumericalReduced
from gym.envs.RoboSkate.RoboSkateSegmentationReduced import RoboSkateSegmentationReduced
from gym.envs.RoboSkate.RoboSkateMultiInputPolicyReduced import RoboSkateMultiInputPolicyReduced
from gym.envs.RoboSkate.RoboSkateNumerical10Obs import RoboSkateNumerical10Obs
from gym.envs.RoboSkate.RoboSkateSegmentation10Obs import RoboSkateSegmentation10Obs










